Updated the OPA tests

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -64,11 +64,18 @@ jobs:
 
     - name: Run OPA Tests
       run: |
-        opaout=$(opa eval --data ../policies/instance-policy.rego --input /tmp/plan.json "data.terraform.deny" | jq -r '.result[].expressions[].value[]')
-        if [ -z "$opaout" ]; then
-          exit 0
+        if opa eval --format pretty --data ../policies/instance-policy.rego --input /tmp/plan.json "data.terraform.deny" > /tmp/opa_output; then
+          violations=$(cat /tmp/opa_output)
+          if [ -z "$violations" ] || [ "$violations" == "[]" ]; then
+            echo "No policy violations found"
+            exit 0
+          else
+            echo "Policy violations found:"
+            echo "$violations"
+            gh pr comment ${{ github.event.pull_request.number }} --body "### Policy Violations Found:\n\n$violations"
+            exit 1
+          fi
         else
-          echo "$opaout"
-          gh pr comment ${{ github.event.pull_request.number }} --body "### $opaout"
+          echo "Error running OPA evaluation"
           exit 1
         fi
